import { Skeleton } from "@/components/ui/skeleton"

type Portal = "admin" | "lecturer"
const accent = { admin: "bg-[#002388]", lecturer: "bg-amber-400" }

function Frame({ portal, titleWidth = "w-56", children }: { portal: Portal; titleWidth?: string; children: React.ReactNode }) {
  return <div className="min-h-full bg-[#f8f9fa] px-4 py-5 md:px-6 lg:px-8"><div className="mx-auto max-w-[1280px] space-y-6">
    <div className="flex items-start justify-between gap-4"><div><div className={`mb-3 h-1.5 w-10 rounded-full ${accent[portal]} animate-pulse`}/><Skeleton className={`h-7 ${titleWidth}`}/><Skeleton className="mt-2 h-3 w-80 max-w-full"/></div><Skeleton className="h-9 w-32 rounded-sm"/></div>{children}
  </div></div>
}

export function PortalDashboardLoader({ portal }: { portal: Portal }) {
  return <Frame portal={portal} titleWidth="w-48"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4},(_,i)=><div key={i} className="rounded-sm border bg-white p-4"><Skeleton className="h-9 w-9 rounded-sm"/><Skeleton className="mt-5 h-7 w-16"/><Skeleton className="mt-2 h-3 w-28"/></div>)}</div><div className="grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><div className="rounded-sm border bg-white p-5"><Skeleton className="h-4 w-36"/><div className="mt-5 grid gap-3 sm:grid-cols-2">{Array.from({length:4},(_,i)=><Skeleton key={i} className="h-24 rounded-sm"/>)}</div></div><div className="rounded-sm border bg-white p-5"><Skeleton className="h-4 w-28"/><div className="mt-5 space-y-3">{Array.from({length:4},(_,i)=><Skeleton key={i} className="h-14 rounded-sm"/>)}</div></div></div></Frame>
}

export function PortalTableLoader({ portal, columns = 5, stats = 0, cards = false }: { portal: Portal; columns?: number; stats?: number; cards?: boolean }) {
  return <Frame portal={portal}>{stats > 0 && <div className={`grid gap-3 sm:grid-cols-2 lg:grid-cols-${Math.min(stats,4)}`}>{Array.from({length:stats},(_,i)=><div key={i} className="rounded-sm border bg-white p-4"><Skeleton className="h-3 w-24"/><Skeleton className="mt-3 h-7 w-14"/></div>)}</div>}<div className="flex flex-wrap items-center justify-between gap-3"><Skeleton className="h-9 w-72 max-w-full rounded-sm"/><div className="flex gap-2"><Skeleton className="h-9 w-24 rounded-sm"/><Skeleton className="h-9 w-28 rounded-sm"/></div></div>{cards ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({length:6},(_,i)=><div key={i} className="rounded-sm border bg-white p-5"><Skeleton className="h-5 w-2/3"/><Skeleton className="mt-3 h-3 w-full"/><Skeleton className="mt-2 h-3 w-4/5"/><div className="mt-5 flex justify-between"><Skeleton className="h-6 w-20"/><Skeleton className="h-8 w-24"/></div></div>)}</div> : <div className="overflow-hidden rounded-sm border bg-white"><div className="grid gap-4 border-b bg-slate-50 px-5 py-3" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{Array.from({length:columns},(_,i)=><Skeleton key={i} className="h-3 w-3/4"/>)}</div>{Array.from({length:7},(_,row)=><div key={row} className="grid items-center gap-4 border-b px-5 py-4 last:border-0" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{Array.from({length:columns},(_,col)=><Skeleton key={col} className={col===0?"h-5 w-4/5":"h-4 w-2/3"}/>)}</div>)}</div>}</Frame>
}

export function PortalFormLoader({ portal, steps = false, sections = 3 }: { portal: Portal; steps?: boolean; sections?: number }) {
  return <Frame portal={portal}>{steps && <div className="rounded-sm border bg-white p-5"><div className="flex gap-5">{Array.from({length:4},(_,i)=><div key={i} className="flex flex-1 items-center gap-3"><Skeleton className="h-7 w-7 rounded-full"/><div className="flex-1"><Skeleton className="h-4 w-20"/><Skeleton className="mt-2 h-3 w-full"/></div></div>)}</div></div>}{Array.from({length:sections},(_,section)=><div key={section} className="rounded-sm border bg-white p-5"><Skeleton className="h-3 w-36"/><div className="mt-5 grid gap-4 md:grid-cols-2">{Array.from({length:4},(_,i)=><div key={i}><Skeleton className="mb-2 h-3 w-24"/><Skeleton className="h-10 w-full rounded-sm"/></div>)}</div></div>)}</Frame>
}

export function PortalDetailLoader({ portal, analytics = false }: { portal: Portal; analytics?: boolean }) {
  return <Frame portal={portal}><div className="rounded-sm border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><Skeleton className="h-6 w-80 max-w-full"/><Skeleton className="mt-2 h-3 w-56"/></div><div className="flex gap-2"><Skeleton className="h-8 w-24"/><Skeleton className="h-8 w-8"/></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{Array.from({length:3},(_,i)=><div key={i}><Skeleton className="h-3 w-20"/><Skeleton className="mt-2 h-5 w-32"/></div>)}</div></div>{analytics && <div className="grid gap-4 md:grid-cols-3">{Array.from({length:3},(_,i)=><div key={i} className="rounded-sm border bg-white p-5"><Skeleton className="h-3 w-24"/><Skeleton className="mx-auto mt-5 h-28 w-28 rounded-full"/></div>)}</div>}<div className="grid gap-4 lg:grid-cols-[1fr_300px]"><div className="rounded-sm border bg-white p-5"><Skeleton className="h-4 w-36"/><div className="mt-5 space-y-4">{Array.from({length:6},(_,i)=><Skeleton key={i} className="h-14 w-full rounded-sm"/>)}</div></div><div className="rounded-sm border bg-white p-5"><Skeleton className="h-4 w-28"/>{Array.from({length:5},(_,i)=><div key={i} className="mt-4"><Skeleton className="h-3 w-20"/><Skeleton className="mt-2 h-4 w-full"/></div>)}</div></div></Frame>
}

export function PortalSettingsLoader({ portal }: { portal: Portal }) {
  return <Frame portal={portal}><div className="grid gap-5 lg:grid-cols-[220px_1fr]"><div className="rounded-sm border bg-white p-3">{Array.from({length:5},(_,i)=><Skeleton key={i} className="mb-2 h-10 w-full rounded-sm"/>)}</div><div className="space-y-4">{Array.from({length:3},(_,section)=><div key={section} className="rounded-sm border bg-white p-5"><Skeleton className="h-5 w-44"/><Skeleton className="mt-2 h-3 w-72"/><div className="mt-5 grid gap-4 sm:grid-cols-2">{Array.from({length:4},(_,i)=><Skeleton key={i} className="h-10 w-full"/>)}</div></div>)}</div></div></Frame>
}
